server:
  port: 8797
  
spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true

koda:
  interview-test:
    api-kengp3-root-url: 'https://kengp3.github.io/'